"""Write docs/parameters.md from python/znmno2_model/params.py (defaults and comments) and the input groups.

usage: python scripts/param_table.py
"""
import re
from pathlib import Path

from znmno2_model.namelist import EXTRA, GROUPS

ROOT = Path(__file__).resolve().parents[1]
src = (ROOT / "python" / "znmno2_model" / "params.py").read_text()
rows = {}
comment = ""
for line in src.splitlines():
    m = re.match(r"\s{4}(\w+): (\w+) = (.+?)(?:\s+# (.*))?$", line)
    if m:
        name, typ, default, c = m.groups()
        rows[name] = (default.strip(), (c or "").strip())

intro = """# Parameters

Every parameter of the corrected model, by input group (`input/default.nml`), with its default and meaning.
Units: cm, s, mol, A, V; electrolyte concentrations in mol/L. The defaults are illustrative values from the
original programs and the literature cited in [model.md](model.md); they are not fitted to a particular cell.
This file is generated by `scripts/param_table.py`.
"""
out = [intro]
out.append("\n## &run\n\n| Name | Default | Meaning |\n|---|---|---|\n"
           "| `mode` | `'corrected'` | `corrected`, or a faithful port of the original programs: `faithful_charge`, "
           "`faithful_phcell` (Fortran and C++ programs) |\n"
           "| `data_dir` | `'python/znmno2_model/data'` | folder of the spline tables (Fortran and C++ programs) |")
for group, names in GROUPS.items():
    names = [n for n in names if n not in EXTRA]
    if not names:
        continue
    out.append(f"\n## &{group}\n\n| Name | Default | Meaning |\n|---|---|---|")
    for n in names:
        d, c = rows[n]
        out.append(f"| `{n}` | `{d}` | {c.replace('|', '/')} |")
out.append("\n## &output\n\n| Name | Default | Meaning |\n|---|---|---|\n"
           "| `file` | `'znmno2_out.txt'` | output table |")
(ROOT / "docs" / "parameters.md").write_text("\n".join(out) + "\n")
print("wrote docs/parameters.md")
